services:
  wave-designer:
    build:
      context: .
      args:
        GIT_COMMIT_HASH: ${GIT_COMMIT_HASH:-}
        GIT_COMMIT_DATE: ${GIT_COMMIT_DATE:-}
    container_name: wave-designer
    ports:
      - "5001:5001"
    environment:
      - WD_HOST=0.0.0.0
      - WD_PORT=5001
      - WD_DEBUG=0
    restart: unless-stopped
